sudo: false
language: scala
scala:
- 2.12.5
script:
- project/bin/scalafmt --test
- sbt ++$TRAVIS_SCALA_VERSION test
jdk:
- oraclejdk8
before_install:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
    openssl aes-256-cbc -K $encrypted_a3b976c9d5d0_key -iv $encrypted_a3b976c9d5d0_iv -in travis/secrets.tar.enc -out travis/secrets.tar -d;
    tar xv -C travis -f travis/secrets.tar;
  fi
- export PATH=${PATH}:./vendor/bundle
install:
- rvm use 2.2.8 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 3.2.1
after_success:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then sbt ++$TRAVIS_SCALA_VERSION releaseEarly;
  fi
- if [ "$TRAVIS_BRANCH" = "$TRAVIS_TAG" ]; then sbt ++$TRAVIS_SCALA_VERSION docs/publishMicrosite;
  fi
env:
  global:
  - secure: na6lTRZ2ulFeBe3OGQ4jbnlpgnr0vk9B5pPvKwM2fbMfNl4bM/vGnqRzD6MbqVhwGg2tuVbnmWK1AD8iFKF99RHG3dekrTD86H71Ew7m2eS7rUZ4LLu86fUCCSRuATKWEtwZCaAquP/pBHEXJlRblZdEWRJulTP0ZUJUrpT3KudEegDta+ACZewhH7VLgDMVjfaV7gFM5wMRPJmBplR5JITyZP9nr4KouIsz1gez/AHDSA9V2rduai4QFKbEjeTQmBf/DdM+Er6WM+oEGjSKYeWDl/voikQaEBvQRyHjrhhVTA3/VrCg42f84Xbau+VSMs1ToSRUr9oEjLdeUIzAUiw32yo8mc9zIGuKK/w/zgtskhClD8eY5lgvxm4MyprGfGcqRQm+PaWqXkmDTn2kKHGB450Or/TyD1wDxda3X+vyKAEqsV1qvDcahHx/pfgMeE+R2KdHZk/da6ADdybUyO8H39xzoadIo6pB7wEceEL6BQoWf3ZfPwBICOV7t34mABbi7kchwRfafXNG7OtBjxEkw5cWcxbK80mSCnycCho91i7Orm6GTvRrrXMITxT02nk1FduyMUsuOzhl084bcJi4GmBMLsoeG5nteJlMB3TQuH6S5AHsHMdGzIbV0j4HTSHwOrI1TmdGzCk/WqkYW35V4lsFzQSZ/rh1aQouSzk=
  - secure: 401ycavN4Hedx8qyiYyCeSWtuK2HjIpln8D2Z9TF33LURHVmZgx3gWQyddo4tJ4qyLMXvuVz8E1yKVYbTS4tJQpyVmCGve/rvnEisHU/nHPulOYaz3Kiupu9H+7yuogxpOxvMPgh6S21NZOO0N5ENvWn4OWdcWrEAqO8/hq7ucfN1bmVk49aA1bhq3N9DtsWUpeeGPRE6WY9yVSzXJoeUTMUnAjWRQAX6FtQhVdMlYwN8Iv+cALH56CLZY/i51VJ79b1CjlQC9hNbvImQy99fok7SAmI5u718b8AeKrrQxald4wUymtLs5xORk+VkQ3M3JAFR/om2JPdeSo2BXNywgu7Y48vMeqPqQ3cFElx8GFC5oDWZG+e4ViWhMS5zXfUAYdDDGTOT/irocS+2z80mQuv1W54eKS66xmAx4Xnu2Ze/w9x5ysybHGQUmVUrw02vFSTq43nR1PbExYmB1KNrQG/TtLoULSk3Mts6R7XVlkHihRy4rl+/FKCePYdL2IXC7e36AA+GJNft+HpOKHwLslFG9KGPFfkNsnVYXd5l3Psppd8gFCM+FruodE/HQLgIUDyLqN9YccZ5nlVhBiKD9toPH7xOXvdH2Ycf46kINit5m0c5d6HMJ30Iw1hogGOD30Gn5h70TQCO2te4Oev2BrRji5VeGdiLPZap/tSJvk=
  - secure: TdiTOBVdnQeliF52WPf4vpLny+jh71n0P6mCFLrGhVYm4j8jBcaIxbuDqv8lVqcNvXdXdQcu8DuLU74S8AS8aqsQFmTJaL0wzTegskTOBdtnFMqP3twJgi79s6TYemxz0VU7xgaH3IGSAolXcTdqQsNmFh8MZM0shx8fur2e2m7G4g8ZMmvyQM2t+7mrcb7UhaW57SXVegZun5VkACYROY2aAwHGJKpLWfhq/6sIMjzF+Yl1TS5BO24lyRC6FLYLtnn9GDCjDoVu2Ot8kwuQp0l6raSNee0ZROdsHfycm6xmDVE0oZMMGg8zR0DJ5RUJGrb5I3l2bk0X+GTHaCSc/LqVfAC2AOwn96gxuuhV3opHcPI5MOosdKHdvx4Wg9X0XMlbiL/1kS/2AZLzVTcDCY4TzAnW6ZILiikVq/sh8vMTFmRJJTNVil82kh4Ah/LQR+fAKfWYMjYOxJMXnVpDZOiw16T6S/OJwxl3uYOhVHrmfHs2LRz4GZh/eyKJzeqcsVUMbbFmeB3yIJxGBUHlUIK4dA+yAhsEUSrqc2OmtKEVu4Da5JG2nj1uCdMUWi5blRrPUcpYQVgCOBRyvqXP32XW+Q/V1s1Fu/TnulpGHvuk9p1GdHXzfYfz0CQh6cOzipxd5CIr5z9PoaGM8+hoEyJTJ3AcDjJAZ+Se/YM6jXQ=
