name: Remder
baseurl: /remder
description: 'Remder: markdown rendered live'
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.11
org: ph.samson.remder
markdown: kramdown
